---
# YAML 1.2
# See: http://yaml.org for more info.  EXP uses the yaml-cpp library
# (http://github.com/jbeder/yaml-cpp) for parsing and emitting YAML
#
# ------------------------------------------------------------------------
# These parameters control the simulation
# ------------------------------------------------------------------------
Global:
  outdir     : /home/someuser/dir
  nbodmax    : 10000
  nthrds     : 1
  dtime      : 0.05
  ldlibdir   : /home/someuser/lib/user
  runtag     : run0
  nsteps     : 100
  multistep  : 8
  dynFracA   : 0.004
  dynFracV   : 0.02
  nreport    : 1
  infile     : OUT.run0.chkpt
  VERBOSE    : 0
  cuda       : off

# ------------------------------------------------------------------------
# This is a sequence of components.  The parameters for the force are
# now included as a parameter map, rather than a separate file.
#
# Each indented stanza beginning with '-' is a component
# ------------------------------------------------------------------------
Components:
  - name       : dark halo
    parameters : {nlevel: 1}
    bodyfile   : halo.bod
    force :
      id : sphereSL
      parameters : {rmax: 9.95}

  - name       : star disk
    parameters : {nlevel: 1}
    bodyfile   : disk.bod
    force :
      id : cylinder
      parameters : {acyl: 1.0, nmax: 8, mmax: 2, hcyl: 0.05}
#
# The parameters could be expressed like this, equivalently:
#
#       parameters :
#         nlevel   : 1
#

# ------------------------------------------------------------------------
# This is a sequence of outputs
# ------------------------------------------------------------------------
Output:
  - id : outlog
    parameters : {nint: 10}
  - id : outpsn
    parameters : {nint: 5}
  - id : outchkpt
    parameters : {nint: 100}
  - id : orbtrace
    parameters : {norb: 5, name: star disk}

# ------------------------------------------------------------------------
# This is a sequence of external forces
# This can be empty (or missing)
# ------------------------------------------------------------------------
External:
# Currently empty

  # Examples . . . 
  # - id : usertest
  #   parameters : {parm: 3}
  # - id : userbar
  #   parameters : {U5: 1.0, comname: sphereSL}
    


# ------------------------------------------------------------------------
# Excluded list of interations as name1 : name2 map entries
# This can be empty (or missing).  By default, all components will
# interact unless interactions are listed below.  This behavior can
# be inverted using the 'allcouples: false' flag in the 'Global' map
# ------------------------------------------------------------------------
Interaction:
  
...
