---
# YAML 1.2
# See: http://yaml.org for more info.  EXP uses the yaml-cpp library
# (http://github.com/jbeder/yaml-cpp) for parsing and emitting YAML
#
# ------------------------------------------------------------------------
# These parameters control the simulation
# ------------------------------------------------------------------------
Global:
  outdir     : /home/someuser/dir
  nbodmax    : 1000000
  nthrds     : 1
  dtime      : 0.005
  ldlibdir   : /home/someuser/lib/user
  runtag     : run0
  nsteps     : 100
  multistep  : 14
  dynFracR   : 0.001
  dynFracV   : 0.01
  dynFracA   : 0.03
  dynFracV   : 0.05
  nreport    : 1
  infile     : OUT.run0.chkpt
  VERBOSE    : 0
  cuda       : off

# ------------------------------------------------------------------------
# This is a sequence of components.  The parameters for the force are
# now included as a parameter map, rather than a separate file.
#
# Each indented stanza beginning with '-' is a component
# ------------------------------------------------------------------------
Components:
  - name       : dark halo
    parameters : {nlevel: 1, indexing: true}
    bodyfile   : halo.bods
    force :
      id : sphereSL
      parameters :
        numr: 4000
        rmin: 0.0001
        rmax: 1.95
        Lmax: 6
        nmax: 20
        rs: 0.0667
        self_consistent: true
        modelname: SLGridSph.model

# ------------------------------------------------------------------------
# This is a sequence of outputs
# ------------------------------------------------------------------------
Output:
  - id : outlog
    parameters : {nint: 10}
  - id : outpsn
    parameters : {nint: 1000}
  - id : outchkpt
    parameters : {nint: 200}

# ------------------------------------------------------------------------
# This is a sequence of external forces
# This can be empty (or missing)
# ------------------------------------------------------------------------
External:

# Currently empty

# ------------------------------------------------------------------------
# List of interations as name1 : name2 map entries
# This can be empty (or missing)
# ------------------------------------------------------------------------
Interaction:

# None: only one component
  
...
