---
# YAML 1.2
# See: http://yaml.org for more info.  EXP uses the yaml-cpp library
# (http://github.com/jbeder/yaml-cpp) for parsing and emitting YAML
#
# ------------------------------------------------------------------------
# These parameters control the simulation
# ------------------------------------------------------------------------
Global:
  outdir     : /home/someuser/dir
  nbodmax    : 1000000
  nthrds     : 1
  dtime      : 0.002
  ldlibdir   : /home/someuser/lib/user
  runtag     : run0
  nsteps     : 100
  multistep  : 8
  dynFracA   : 0.004
  dynFracV   : 0.02
  infile     : OUT.run0.chkpt
  VERBOSE    : 0
  cuda       : off

# ------------------------------------------------------------------------
# This is a sequence of components.  The parameters for the force are
# now included as a parameter map, rather than a separate file.
#
# Each indented stanza beginning with '-' is a component
# ------------------------------------------------------------------------
Components:
  - name       : dark halo
    parameters : {nlevel: 1, EJ: 2, EJdamp: 1.0, nEJkeep: 256, nEJwant: 1000, com_log: 1, EJdryrun: true, indexing: true}
    bodyfile   : halo.bods
    force :
      id : sphereSL
      parameters : {numr: 2000, rmin: 0.0001, rmax: 1.95, Lmax: 6, nmax: 20, rs: 0.0667, self_consistent: true, modelname: SLGridSph.model, pca: true, pcadiag: true, pcavtk: true, npca: 100, tk_type: Hall}

  - name       : star disk
    parameters : {nlevel: 1, EJdamp: 0.8, EJdryrun: true, EJ: 2, nEJkeep: 256, nEJwant: 500, EJkinE: false, EJext: false, EJdiag: false, EJdT: 1.0e-8, indexing: true}
    bodyfile   : disk.bods
    force :
      id : cylinder
      parameters : {acyl: 0.01, hcyl: 0.001, lmax: 32, mmax: 6, nmax: 32, ncylorder: 8, ncylnx: 256, ncylny: 128, rnum: 200, pnum: 80, tnum: 80, ashift: 0.5, vflag: 0, logr: false, self_consistent: true, pca: true, npca: 100, pcadiag: true, pcavtk: true, tk_type: Hall}
#
# The parameters could be expressed like this, equivalently:
#
#       parameters :
#         nlevel   : 1
#         EJdamp   : 0.8
#         EJdryrun : 1
#         EJ       : 2
#         nEJkeep  : 256
#         nEJwant  : 500
#         EJkinE   : 0
#         EJext    : 0
#         EJdiag   : 0
#         EJdT     : 1.0e-8
#         indexing : true

# ------------------------------------------------------------------------
# This is a sequence of outputs
# ------------------------------------------------------------------------
Output:
  - id : outlog
    parameters : {nint: 10}
  - id : outpsn
    parameters : {nint: 5}
  - id : outchkpt
    parameters : {nint: 100}
  - id : orbtrace
    parameters : {norb: 5, name: star disk}
  - id : outdiag
    parameters : {nint: 3}

# ------------------------------------------------------------------------
# This is a sequence of external forces
# This can be empty (or missing)
# ------------------------------------------------------------------------
External:

# Currently empty

# ------------------------------------------------------------------------
# Excluded list of interations as name1 : name2 map entries
# This can be empty (or missing).  By default, all components will
# interact unless interactions are listed below.  This behavior can
# be inverted using the 'allcouples: false' flag in the 'Global' map
# ------------------------------------------------------------------------
Interaction:
  
...
